### PR TITLE
style(input): add margin left to clear icon

### LINKED ISSUE #57: tree select 鼠标经过严重抖动
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** arco-design-vue
- **系统版本:** macOS Big Sur 11.6
- **浏览器版本:** Chrome 95.0.4638.54
- **复现地址:** https://arco.design/vue/component/tree-select#checkable

## 预期结果
鼠标经过不抖动，并且在宽度足够的情况下，不换行

## 复现步骤
点击选择器，勾选几个节点，失去焦点后，鼠标再次经过选择器，会发生严重抖动，react版不会出现此情况
image
额外的换行

image
鼠标经过抖动

### PR DESCRIPTION
**Pull request by ChuChencheng**
## Types of changes

- [ ] New feature
- [ ] Bug fix
- [ ] Documentation change
- [ ] Coding style change
- [x] Component style change
- [ ] Refactoring
- [ ] Performance improvement
- [ ] Test cases
- [ ] Continuous integration
- [ ] Typescript definition change
- [ ] Breaking change
- [ ] Others

## Background and context

Fixes #57 

There is a left padding on the suffix icon while the clear icon has no padding or margin. And this may make the Input element blinking on hover.

image
image

## Solution

Add `margin-left` to clear icon.

## Changelog

| Component | Changelog(CN) | Changelog(EN) | Related issues |
| --------- | ------------- | ------------- | -------------- |
| input | 修改 `clear-btn` 样式，解决 `select-view` 可能会抖动的问题 | Modify the style of `clear-btn` to solve the problem that `select-view` may jitter | Close #57  |

## Checklist:

- [x] Test suite passes (`npm run test`)
- [x] Provide changelog for relevant changes (e.g. bug fixes and new features) if applicable.
- [x] Changes are submitted to the appropriate branch (e.g. features should be submitted to `feature` branch and others
  should be submitted to `main` branch)

### CODE REVIEW

**Comment by Flsion** [comment]
@ChuChencheng 嗨，你好，感谢pr。这个clear-btn增加marginLeft的方法，在有多个suffix图标的情况下也会存在一些问题，这里可以试试将suffix的dispaly:none改成visibility: hidden，然后把clearBtn改成absolute的定位方式

**Comment by ChuChencheng** [comment]
能麻烦提供一下多个 suffix 问题的具体示例么，我这边没复现出问题。

目前 clear btn 是放在 suffix icon 前面的，这边是希望 hover 时隐藏 suffix icon 么？

image

**Comment by Flsion** [comment]
是的，input-tag有个hideSuffixOnClear的隐藏属性，select和select-tree等下拉组件是开启这个属性的，在显示clear-btn时会隐藏到suffix，并在上方展示按钮。可以看下_components/select-view组件

**Comment by Flsion** [comment]
我试了一下其他方案，也不是能很好解决多suffix的问题，就采用这个方法啦

**Pull request merged**
