### PR TITLE
fix(modal): add width attribute, fullscreen width become invalid.

### LINKED ISSUE #2440: Modal组件同时设置了width和fullscreen属性后，fullscreen宽度不能铺满屏幕
[在线地址](https://codesandbox.io/s/elated-payne-19x7vz?file=/src/App.vue)

### PR DESCRIPTION
**Pull request by lq9958**
## Types of changes

- [ ] New feature
- [x] Bug fix
- [ ] Enhancement
- [ ] Component style change
- [ ] Typescript definition change
- [ ] Documentation change
- [ ] Coding style change
- [ ] Refactoring
- [ ] Test cases
- [ ] Continuous integration
- [ ] Breaking change
- [ ] Others

## Changelog

| Component | Changelog(CN) | Changelog(EN) | Related issues |
| --------- | ------------- | ------------- | -------------- |
|    modal       |    修复同时设置 `width` 和 `fullscreen` 时，没有全屏的问题     |    Fix the problem that there is no full screen when `width` and `fullscreen` are set at the same time     |        Close  #2440        | 

## Checklist:

- [ ] Test suite passes (`npm run test`)
- [ ] Provide changelog for relevant changes (e.g. bug fixes and new features) if applicable.
- [ ] Changes are submitted to the appropriate branch (e.g. features should be submitted to `feature` branch and others
  should be submitted to `main` branch)

### CODE REVIEW

**Comment by Aweerrweer** [comment]
单独设置width无效么？

**Comment by jbhvip** [comment]
仍不能设置宽度

**Comment by lq9958** [comment]
> 单独设置width无效么？
请复现一下，并给出线上地址

**Comment by lq9958** [comment]
> 仍不能设置宽度
modal 的默认宽度为520px, 马上就修

**Comment by lq9958** [comment]
> 单独设置width无效么？

确实有问题，马上就修

**Comment by zhangfei1111** [comment]
修好了吗

**Comment by icecream4k** [comment]
还没修好么，影响业务功能了已经

**Comment by wanziheima** [comment]
何时修改好啊

**Pull request merged**
