### PR TITLE
add function rowclass for table.tsx

### PR DESCRIPTION
**Pull request by tetris1128**
为Table组件增加动态的rowClassName支持
Added function based rowClassName support in the table component

## Types of changes

- [ ] New feature
- [ ] Bug fix
- [x] Enhancement
- [ ] Component style change
- [ ] Typescript definition change
- [ ] Documentation change
- [ ] Coding style change
- [ ] Refactoring
- [ ] Test cases
- [ ] Continuous integration
- [ ] Breaking change
- [ ] Others

## Background and context
当前版本的rowClass无法动态，只能给固定的，无法进行灵活业务逻辑操作。

## Solution
为rowClass增加function类型的参数，同时将数据以及行索引带入function中。

## How is the change tested?
```
//为Table增加row-class="testFunc"
 <a-table
        :row-class="testFunc"
        v-bind="getBindValues"
        :pagination="pagination"
        page-position="br"
        :hide-expand-button-on-empty="true"
        @page-change="handlePageChange"
        @page-size-change="handlePageSizeChange"
        @select="handleSelect"
        @select-all="handleSelectAll"
        @row-click="clickRowData"
        @cell-click="clickCellData"
        @sorter-change="sorterChange"
        class="basicTable"
      >
      </a-table>
//增加函数
const testFunc= (record, rowIndex) => {
    //具体业务逻辑
}
```

## Changelog

| Component | Changelog(CN) | Changelog(EN) | Related issues |
| --------- | ------------- | ------------- | -------------- |
|  table  |  rowClass 支持函数类型的值     |  rowClass supports values of function types |                |

## Checklist:

- [x] Test suite passes (`npm run test`)
- [x] Provide changelog for relevant changes (e.g. bug fixes and new features) if applicable.
- [ ] Changes are submitted to the appropriate branch (e.g. features should be submitted to `feature` branch and others
  should be submitted to `main` branch)

### CODE REVIEW

**Comment by yaoyuana** [comment]
这个rowCLass好坑

**Comment by yaoyuana** [comment]
支持版本号也不在官方文档上更新，一度怀疑自己傻掉了，竟然不支持///////////////

**Comment by yaoyuana** [comment]
微信图片_20220817135218

**Comment by tetris1128** [comment]
哈哈哈哈哈 文档没更新



---Original---
From: ***@***.***&gt;
Date: Wed, Aug 17, 2022 13:52 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [arco-design/arco-design-vue] add function rowclass for table.tsx (PR #1453)

**Comment by yaoyuana** [comment]
还笑，看我梆梆两拳

**Pull request merged**
