### PR TITLE
fix(datepicker): rename useState to useSetState (#1720)

### PR DESCRIPTION
**Pull request by cyan113**
## Types of changes

- [ ] New feature
- [x] Bug fix
- [ ] Enhancement
- [ ] Component style change
- [ ] Typescript definition change
- [ ] Documentation change
- [ ] Coding style change
- [ ] Refactoring
- [ ] Test cases
- [ ] Continuous integration
- [ ] Breaking change
- [ ] Others

## Changelog

| Component | Changelog(CN) | Changelog(EN) | Related issues |
| --------- | ------------- | ------------- | -------------- |
| DatePicker | 将useState重命名为useSetState | rename useState to useSetState | #1720 |
| TimePicker | 将useState重命名为useSetState | rename useState to useSetState | #1720 |

## Checklist:

- [ ] Test suite passes (`npm run test`)
- [ ] Provide changelog for relevant changes (e.g. bug fixes and new features) if applicable.
- [ ] Changes are submitted to the appropriate branch (e.g. features should be submitted to `feature` branch and others
  should be submitted to `main` branch)

### CODE REVIEW

**Comment by flsion** [comment]
@cyan113 没有太明白这里修改的目的，`useState` 这个函数在 vue 中没有被使用，和 react 不一样，应该不存在命名冲突的问题

**Comment by cyan113** [comment]
这主要针对nuxt的修改，`useState` 在nuxt中被使用，重命名可以解决 #1720

[https://nuxt.com/docs/api/composables/use-state](https://nuxt.com/docs/api/composables/use-state)
`useState` is a reserved function name transformed by the compiler, so you should not name your own function useState.

**Comment by lonquan** [comment]
可考虑合并下, 被这个问题折磨几天了 😢

**Comment by ItsRyanWu** [comment]
可以从 Nuxt 层面解决
https://github.com/nuxt/nuxt/pull/20955

**Pull request closed without merging**
