### PR TITLE
fix(color-picker): fix issue control bar shaking when v-model

### PR DESCRIPTION
**Pull request by tujindong**
## Types of changes

- [ ] New feature
- [x] Bug fix
- [ ] Enhancement
- [ ] Component style change
- [ ] Typescript definition change
- [ ] Documentation change
- [ ] Coding style change
- [ ] Refactoring
- [ ] Test cases
- [ ] Continuous integration
- [ ] Breaking change
- [ ] Others

## Background and context

ColorPicker 在设置v-model 情况下，在色板取色拖动过程中，下方的色调指示器抖动，特别是靠近左下方区域，取色器灵敏度降低，触及取色器左下方边界位置，色调指示器会直接跳动到最左边。

## Changelog

| Type | Component | Changelog(CN) | Changelog(EN) | Related issues |
|-------| --------- | ------------- | ------------- | -------------- |
| fix | color-picker | 修复v-model情况下色调指示器抖动问题 |   fix issue control bar shaking when v-model | Open [#3174](https://github.com/arco-design/arco-design-vue/issues/3174) |

## Checklist:

- [x] Test suite passes (`npm run test`)
- [x] Provide changelog for relevant changes (e.g. bug fixes and new features) if applicable.
- [x] Changes are submitted to the appropriate branch (e.g. features should be submitted to `feature` branch and others
  should be submitted to `main` branch)

### CODE REVIEW

**Review by oljc — COMMENTED** [review]
@tujindong 你这样好像并未解决问题🤔

**Comment by tujindong** [comment]
@oljc 应该是色板指示器的位置处理还未解决，我可以补充一下这部分的逻辑。

**Comment by oljc** [comment]
> @oljc 应该是色板指示器的位置处理还未解决，我可以补充一下这部分的逻辑。

要是麻烦的话 我来处理吧，你这个改动有点问题感觉没有意义控制条还失去了响应。

**Comment by tujindong** [comment]
好的 期待新版本发布。

**Pull request closed without merging**
