### PR TITLE
enhance(descriptions): 新增 tableLayout属性

### LINKED ISSUE #1345: Descriptions可以添加tableLayout功能吗
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 现有案例
tableLayout	描述中表格样式的 layout-fixed，当设置成 fixed 时，宽度会均分。	'auto' | 'fixed'	auto
https://arco.design/react/components/descriptions#api

## 预期解决问题
可以实现让表格等分布局

### PR DESCRIPTION
**Pull request by czq297297**
## Types of changes

- [x] New feature
- [ ] Bug fix
- [ ] Enhancement
- [ ] Component style change
- [ ] Typescript definition change
- [ ] Documentation change
- [ ] Coding style change
- [ ] Refactoring
- [ ] Test cases
- [ ] Continuous integration
- [ ] Breaking change
- [ ] Others

## Changelog

| Component | Changelog(CN) | Changelog(EN) | Related issues |
| --------- | ------------- | ------------- | -------------- |
| Description |描述中表格样式的 `layout-fixed`，当设置成 `fixed` 时，宽度会均分 | The `layout-fixed` of the table style in the description. The width will be evenly distributed when it's set to `fixed`.|     Close #1345         |

## Checklist:

- [x] Test suite passes (`npm run test`)
- [x] Provide changelog for relevant changes (e.g. bug fixes and new features) if applicable.
- [ ] Changes are submitted to the appropriate branch (e.g. features should be submitted to `feature` branch and others
  should be submitted to `main` branch)

### CODE REVIEW

**Comment by hehehai** [comment]
这里建议直接用属性 `fixedColumn: boolean`，默认为 `false`。`table-layout` 的值仅有 `auto | fixed`。

**Comment by hehehai** [comment]
可以调整下 [Layout demo](https://arco.design/vue/component/descriptions#layout)

```vue
<template>
  <a-space size="large">
    <a-radio-group type="button" v-model="size">
      <a-radio value="mini">mini</a-radio>
      <a-radio value="small">small</a-radio>
      <a-radio value="medium">medium</a-radio>
      <a-radio value="large">large</a-radio>
    </a-radio-group>
    <div>
      <span>均分列宽：</span>
      <a-switch v-model="isFixedColumn"/>
    </div>
  </a-space>
  <a-space direction="vertical" fill style="margin-top: 20px">
    <a-descriptions :table-layout="isFixedColumn ? 'fixed' : 'auto'" :data="data" :size="size" title="User Info (horizontal)" bordered />
    <a-descriptions :table-layout="isFixedColumn ? 'fixed' : 'auto'" :data="data" :size="size" title="User Info (inline-horizontal)" layout="inline-horizontal" bordered />
    <a-descriptions :table-layout="isFixedColumn ? 'fixed' : 'auto'" :data="data" :size="size" title="User Info (vertical)" layout="vertical" bordered />
    <a-descriptions :table-layout="isFixedColumn ? 'fixed' : 'auto'" :data="data" :size="size" title="User Info (inline-vertical)" layout="inline-vertical" bordered />
    <a-descriptions :table-layout="isFixedColumn ? 'fixed' : 'auto'" :data="data" :size="size" title="User Info (inline-vertical)" layout="inline-vertical" bordered />
  </a-space>
</template>

<script>
import { ref } from 'vue';

export default {
  setup() {
    const size = ref('medium');
    const isFixedColumn = ref(false)

    const data = [{
      label: 'Name',
      value: 'Socrates',
    }, {
      label: 'Mobile',
      value: '123-1234-1234',
    }, {
      label: 'Residence',
      value: 'Beijing'
    }, {
      label: 'Hometown',
      value: 'Beijing',
    }, {
      label: 'Address',
      value: 'Yingdu Building, Zhichun Road, Beijing'
    }];

    return {
      data,
      size,
      isFixedColumn,
    }
  },
}
</script>
```

image

**Comment by liziwork** [comment]
老哥，更新了吗？

**Comment by czq297297** [comment]
> 

2.38.0版本更新

**Comment by czq297297** [comment]
>

**Comment by czq297297** [comment]
> 老哥，更新了吗？

2.38.0版本更新

**Comment by Mr-Yel** [comment]
均分列宽的时候label也一起均分了是不是不太合理，有办法让内容均分列宽但是label保持不变吗

**Pull request merged**
