### PR TITLE
feat(verification-code): add verification-code component

### PR DESCRIPTION
**Pull request by LIjiAngChen8**
## Types of changes

- [x] New feature
- [ ] Bug fix
- [ ] Enhancement
- [ ] Component style change
- [ ] Typescript definition change
- [ ] Documentation change
- [ ] Coding style change
- [ ] Refactoring
- [ ] Test cases
- [ ] Continuous integration
- [ ] Breaking change
- [ ] Others

## Background and context

 [验证码输入框 VerificationCode](https://arco.design/react/components/verification-code)

## Solutio

image

https://github.com/arco-design/arco-design-vue/assets/48879481/62541059-c250-4c6d-ad45-17710217499f

image

## Changelog

| Component | Changelog(CN) | Changelog(EN) | Related issues |
| --------- | ------------- | ------------- | -------------- |
|    VerificationCode       |     新增验证码输入组件          |   add verification-code  component       |                |

## Checklist:

- [x] Test suite passes (`npm run test`)
- [x] Provide changelog for relevant changes (e.g. bug fixes and new features) if applicable.
- [x] Changes are submitted to the appropriate branch (e.g. features should be submitted to `feature` branch and others
  should be submitted to `main` branch)

### CODE REVIEW

**Comment by flsion** [comment]
@LIjiAngChen8 你速度好快👍🏻

**Comment by Loongphy** [comment]
等一个合并

**Comment by kaikaibenkai** [comment]
您 很强

**Comment by beijin1949** [comment]
请问这个只要react更新了吗

**Comment by LIjiAngChen8** [comment]
> 请问这个只要react更新了吗

@beijin1949 Vue 2.54.0 以上可以使用

**Pull request merged**
