### PR TITLE
feat(color-picker): add color-picker component

### LINKED ISSUE #2383: 希望增加 颜色选择器 组件
希望增加 颜色选择器 组件，找了几遍，好像没看到

### LINKED ISSUE #2752: 能添加一个颜色选择器吗
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.52.1
- **Browser:** chrome118.0.0.0

### LINKED ISSUE #2951: 可以加个颜色选择器吗
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## What problem does this feature solve?
什么时候可以加颜色选择器，看react版都有了 vue的什么时候才能上

## What are the similar cases of this feature
什么时候可以加颜色选择器，看react版都有了 vue的什么时候才能上

### PR DESCRIPTION
**Pull request by LIjiAngChen8**
## Types of changes

- [x] New feature
- [ ] Bug fix
- [ ] Enhancement
- [ ] Component style change
- [ ] Typescript definition change
- [ ] Documentation change
- [ ] Coding style change
- [ ] Refactoring
- [ ] Test cases
- [ ] Continuous integration
- [ ] Breaking change
- [ ] Others

## Background and context

**颜色选择器 ColorPicker**

## Solution

代码主逻辑 / 风格样式 与 [React](https://arco.design/react/components/color-picker) 版颜色选择器一致。

**API:**
image
image

https://github.com/arco-design/arco-design-vue/assets/48879481/1867b469-aa25-4399-9b10-58e7c21c81ef

## Changelog

| Component | Changelog(CN) | Changelog(EN) | Related issues |
| --------- | ------------- | ------------- | -------------- |
|   color-picker    |  新增颜色选择器  |   add color-picker component        |   Closes #2951, Closes #2752, Closes #2383    |

## Checklist:

- [x] Test suite passes (`npm run test`)
- [x] Provide changelog for relevant changes (e.g. bug fixes and new features) if applicable.
- [x] Changes are submitted to the appropriate branch (e.g. features should be submitted to `feature` branch and others
  should be submitted to `main` branch)

### CODE REVIEW

**Comment by flsion** [comment]
@LIjiAngChen8 强👍🏻

**Comment by Loongphy** [comment]
快男

**Comment by Free0520** [comment]
可以增加一个吸管功能吗，或者给个插槽 @flsion

**Comment by flsion** [comment]
> 可以增加一个吸管功能吗，或者给个插槽 @flsion

下个版本会加个自定义插槽

**Comment by chenbimo** [comment]
好像还没在文档中看到这个组件，这个很不错，希望增加更多组件，感谢团队的辛苦工作~

**Comment by 3529** [comment]
颜色选择器貌似有BUG。双向绑定有问题，比如对颜色进行赋值，界面无更新。
```vue
<template>
  <a-space>
    <a-color-picker v-model="value" />
    {{ value }}

  </a-space>
</template>

<script setup>
import { ref } from 'vue';
const value = ref('#165DFF');
setTimeout(() => {
  value.value = '#ff5500';
}, 500);
</script>

```

**Comment by kellehod** [comment]
> 颜色选择器貌似有BUG。双向绑定有问题，比如对颜色进行赋值，界面无更新。
> 
> ```
> <template>
>   <a-space>
>     <a-color-picker v-model="value" />
>     {{ value }}
> 
>   </a-space>
> </template>
> 
> <script setup>
> import { ref } from 'vue';
> const value = ref('#165DFF');
> setTimeout(() => {
>   value.value = '#ff5500';
> }, 500);
> </script>
> ```

也遇到了这个问题

**Comment by lw9810** [comment]
import { defineComponent } from 'vue';

export default defineComponent({
  setup() {
    const colorCode = ref('#ff5500');
    return () => (
      <>
        <a-color-picker showPreset default-value={colorCode} v-model={colorCode} />
      </>
    );
  }
});
对颜色进行双向绑定的时候初始视图不变，单独设置default-value 有效  ，设置default-value 同时双向绑定初始视图不变

**Pull request merged**
